image:https://gitlab.com/susurrus/serialport-rs/badges/master/build.svg[link="https://gitlab.com/susurrus/serialport-rs/pipelines"]
image:https://ci.appveyor.com/api/projects/status/gitlab/Susurrus/serialport-rs?svg=true&branch=master[link="https://ci.appveyor.com/project/Susurrus/serialport-rs"]
image:https://travis-ci.org/Susurrus/serialport-rs.svg?branch=master[link="https://travis-ci.org/Susurrus/serialport-rs"]

image:https://img.shields.io/crates/v/serialport.svg[link="https://crates.io/crates/serialport"]
image:https://docs.rs/serialport/badge.svg[link="https://docs.rs/crate/serialport"]

== Overview

serialport-rs is a general-purpose cross-platform serial port library for Rust. It provides a
simple blocking I/O interface and port enumeration on POSIX and Windows systems. It reuses
code from the https://github.com/dcuddeback/serial-rs[serial-rs] library and aims to provide a
very similar interface to that of the https://doc.qt.io/qt-5/qserialport.html[QSerialPort]
library.

== Feature Overview

The library has been organized such that there is a high-level `SerialPort` trait that provides
a cross-platform API for accessing serial ports. This is the preferred method of interacting
with ports and as such is part of the `prelude`. The `open*()` and `available_ports()` functions in
the root are also cross-platform.

For platform-specific functionality, this crate is split into a `posix` and `windows` API with
corresponding `TTYPort` and `COMPort` structs that both implement the `SerialPort` trait. Using
the platform-specific `open*()` functions will return the platform-specific port object which
allows access to platform-specific functionality.

== Rationale

This library is effectively a fork of the https://github.com/dcuddeback/serial-rs[serial-rs]
library and was created as that library was slow to include enumeration support. I had also
previously used the QSerialPort library and preferred that API to the one provided by serial-rs.

== Dependencies

Rust versions 1.13 and higher are supported.

== Platform Support

Operating system support is as follows:

Tier 1:

  * Linux, i686 & x86_64

Tier 2:

  * Windows 7+, i686 & x86_64
  * Mac OS X

Tier 1 supports means this library is build- and run-tested and is regularly used so this should
be pretty bug-free. Tier 2 means it's only build- and run-tested, but no developer uses this as
their primary development environment.

== Licensing

Licensed under the https://www.mozilla.org/en-US/MPL/2.0/[Mozilla Public License, version 2.0].

== Contributing

Please open an issue or merge request on GitLab to contibute. Code contributions submitted for
inclusion in the work by you, as defined in the MPL2.0 license, shall be licensed as the above
without any additional terms or conditions.

== Acknowledgements

Special thanks to dcuddeback, willem66745, and apoloval who wrote the original serial-rs library
which this library heavily borrows from.

Additionally I'd like to acknowledge the following people who have made contributions:

  * Dave Hylands
  * Zac Berkowitz
