#![allow(non_camel_case_types, dead_code)]

use std::io;
use std::os::fd::AsFd;
use std::slice;
use std::time::Duration;

#[cfg(not(target_os = "linux"))]
use nix::poll::PollTimeout;
use nix::poll::{PollFd, PollFlags};
#[cfg(target_os = "linux")]
use nix::sys::signal::SigSet;
#[cfg(target_os = "linux")]
use nix::sys::time::TimeSpec;
#[cfg(not(target_os = "linux"))]
use std::io::ErrorKind;

pub fn wait_read_fd<F: AsFd>(fd: F, timeout: Duration) -> io::Result<()> {
    wait_fd(fd, PollFlags::POLLIN, timeout)
}

pub fn wait_write_fd<F: AsFd>(fd: F, timeout: Duration) -> io::Result<()> {
    wait_fd(fd, PollFlags::POLLOUT, timeout)
}

fn wait_fd<F: AsFd>(fd: F, events: PollFlags, timeout: Duration) -> io::Result<()> {
    use nix::errno::Errno::{EIO, EPIPE};

    let mut fd = PollFd::new(fd.as_fd(), events);

    #[cfg(target_os = "linux")]
    let wait_res = {
        let timespec = TimeSpec::from_duration(timeout);
        nix::poll::ppoll(
            slice::from_mut(&mut fd),
            Some(timespec),
            Some(SigSet::empty()),
        )
    };
    #[cfg(not(target_os = "linux"))]
    let wait_res = nix::poll::poll(
        slice::from_mut(&mut fd),
        PollTimeout::try_from(timeout.as_millis())
            .map_err(|e| io::Error::new(ErrorKind::InvalidInput, e))?,
    );

    let wait = match wait_res {
        Ok(r) => r,
        Err(e) => return Err(io::Error::from(crate::Error::from(e))),
    };
    // All errors generated by poll or ppoll are already caught by the nix wrapper around libc, so
    // here we only need to check if there's at least 1 event
    if wait != 1 {
        return Err(io::Error::new(
            io::ErrorKind::TimedOut,
            "Operation timed out",
        ));
    }

    // Check the result of ppoll() by looking at the revents field
    match fd.revents() {
        Some(e) if e == events => return Ok(()),
        // If there was a hangout or invalid request
        Some(e) if e.contains(PollFlags::POLLHUP) || e.contains(PollFlags::POLLNVAL) => {
            return Err(io::Error::new(io::ErrorKind::BrokenPipe, EPIPE.desc()));
        }
        Some(_) | None => (),
    }

    Err(io::Error::new(io::ErrorKind::Other, EIO.desc()))
}
