//! serialport-rs is a cross-platform serial port library.
//!
//! The goal of this library is to expose a cross-platform and platform-specific API for enumerating
//! and using blocking I/O with serial ports. This library exposes a similar API to that provided
//! by [Qt's `QSerialPort` library](https://doc.qt.io/qt-5/qserialport.html).
//!
//! # Feature Overview
//!
//! The library has been organized such that there is a high-level `SerialPort` trait that provides
//! a cross-platform API for accessing serial ports. This is the preferred method of interacting
//! with ports. The `SerialPort::new().open*()` and `available_ports()` functions in the root
//! provide cross-platform functionality.
//!
//! For platform-specific functionality, this crate is split into a `posix` and `windows` API with
//! corresponding `TTYPort` and `COMPort` structs (that both implement the `SerialPort` trait).
//! Using the platform-specific `SerialPort::new().open*()` functions will return the
//! platform-specific port object which allows access to platform-specific functionality.

#![allow(clippy::uninlined_format_args)]
#![deny(
    clippy::dbg_macro,
    missing_docs,
    missing_debug_implementations,
    missing_copy_implementations
)]
// Document feature-gated elements on docs.rs. See
// https://doc.rust-lang.org/rustdoc/unstable-features.html?highlight=doc(cfg#doccfg-recording-what-platforms-or-features-are-required-for-code-to-be-present
// and
// https://doc.rust-lang.org/rustdoc/unstable-features.html#doc_auto_cfg-automatically-generate-doccfg
// with its latest update https://github.com/rust-lang/rust/pull/138907 for details.
#![cfg_attr(docsrs, feature(doc_cfg))]
// Don't worry about needing to `unwrap()` or otherwise handle some results in
// doc tests.
#![doc(test(attr(allow(unused_must_use))))]

use std::error::Error as StdError;
use std::fmt;
use std::io;
use std::num::{IntErrorKind, ParseIntError};
use std::str::FromStr;
use std::time::Duration;

#[cfg(unix)]
mod posix;
#[cfg(unix)]
pub use posix::{BreakDuration, TTYPort};

#[cfg(windows)]
mod windows;
#[cfg(windows)]
pub use windows::COMPort;

#[cfg(test)]
pub(crate) mod tests;

/// A type for results generated by interacting with serial ports
///
/// The `Err` type is hard-wired to [`serialport::Error`](struct.Error.html).
pub type Result<T> = std::result::Result<T, Error>;

/// Categories of errors that can occur when interacting with serial ports
///
/// This list is intended to grow over time and it is not recommended to
/// exhaustively match against it.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ErrorKind {
    /// The device is not available.
    ///
    /// This could indicate that the device is in use by another process or was
    /// disconnected while performing I/O.
    NoDevice,

    /// A parameter was incorrect.
    InvalidInput,

    /// An unknown error occurred.
    Unknown,

    /// An I/O error occurred.
    ///
    /// The type of I/O error is determined by the inner `io::ErrorKind`.
    Io(io::ErrorKind),
}

/// An error type for serial port operations
#[derive(Debug, Clone)]
pub struct Error {
    /// The kind of error this is
    pub kind: ErrorKind,
    /// A description of the error suitable for end-users
    pub description: String,
}

impl Error {
    /// Instantiates a new error
    pub fn new<T: Into<String>>(kind: ErrorKind, description: T) -> Self {
        Error {
            kind,
            description: description.into(),
        }
    }

    /// Returns the corresponding `ErrorKind` for this error.
    pub fn kind(&self) -> ErrorKind {
        self.kind
    }
}

impl fmt::Display for Error {
    fn fmt(&self, fmt: &mut fmt::Formatter) -> std::result::Result<(), fmt::Error> {
        fmt.write_str(&self.description)
    }
}

impl StdError for Error {
    fn description(&self) -> &str {
        &self.description
    }
}

impl From<io::Error> for Error {
    fn from(io_error: io::Error) -> Error {
        Error::new(ErrorKind::Io(io_error.kind()), format!("{}", io_error))
    }
}

impl From<Error> for io::Error {
    fn from(error: Error) -> io::Error {
        let kind = match error.kind {
            ErrorKind::NoDevice => io::ErrorKind::NotFound,
            ErrorKind::InvalidInput => io::ErrorKind::InvalidInput,
            ErrorKind::Unknown => io::ErrorKind::Other,
            ErrorKind::Io(kind) => kind,
        };

        io::Error::new(kind, error.description)
    }
}

/// Number of bits per character
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum DataBits {
    /// 5 bits per character
    Five,

    /// 6 bits per character
    Six,

    /// 7 bits per character
    Seven,

    /// 8 bits per character
    Eight,
}

impl fmt::Display for DataBits {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match *self {
            DataBits::Five => write!(f, "Five"),
            DataBits::Six => write!(f, "Six"),
            DataBits::Seven => write!(f, "Seven"),
            DataBits::Eight => write!(f, "Eight"),
        }
    }
}

impl From<DataBits> for u8 {
    fn from(value: DataBits) -> Self {
        match value {
            DataBits::Five => 5,
            DataBits::Six => 6,
            DataBits::Seven => 7,
            DataBits::Eight => 8,
        }
    }
}

impl TryFrom<u8> for DataBits {
    type Error = ();

    fn try_from(value: u8) -> core::result::Result<Self, Self::Error> {
        match value {
            5 => Ok(Self::Five),
            6 => Ok(Self::Six),
            7 => Ok(Self::Seven),
            8 => Ok(Self::Eight),
            _ => Err(()),
        }
    }
}

/// Parity checking modes
///
/// When parity checking is enabled (`Odd` or `Even`) an extra bit is transmitted with
/// each character. The value of the parity bit is arranged so that the number of 1 bits in the
/// character (including the parity bit) is an even number (`Even`) or an odd number
/// (`Odd`).
///
/// Parity checking is disabled by setting `None`, in which case parity bits are not
/// transmitted.
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum Parity {
    /// No parity bit.
    None,

    /// Parity bit sets odd number of 1 bits.
    Odd,

    /// Parity bit sets even number of 1 bits.
    Even,
}

impl fmt::Display for Parity {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match *self {
            Parity::None => write!(f, "None"),
            Parity::Odd => write!(f, "Odd"),
            Parity::Even => write!(f, "Even"),
        }
    }
}

/// Number of stop bits
///
/// Stop bits are transmitted after every character.
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum StopBits {
    /// One stop bit.
    One,

    /// Two stop bits.
    Two,
}

impl fmt::Display for StopBits {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match *self {
            StopBits::One => write!(f, "One"),
            StopBits::Two => write!(f, "Two"),
        }
    }
}

impl From<StopBits> for u8 {
    fn from(value: StopBits) -> Self {
        match value {
            StopBits::One => 1,
            StopBits::Two => 2,
        }
    }
}

impl TryFrom<u8> for StopBits {
    type Error = ();

    fn try_from(value: u8) -> core::result::Result<Self, Self::Error> {
        match value {
            1 => Ok(Self::One),
            2 => Ok(Self::Two),
            _ => Err(()),
        }
    }
}

/// Flow control modes
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum FlowControl {
    /// No flow control.
    None,

    /// Flow control using XON/XOFF bytes.
    Software,

    /// Flow control using RTS/CTS signals.
    Hardware,
}

impl fmt::Display for FlowControl {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match *self {
            FlowControl::None => write!(f, "None"),
            FlowControl::Software => write!(f, "Software"),
            FlowControl::Hardware => write!(f, "Hardware"),
        }
    }
}

impl FromStr for FlowControl {
    type Err = ();

    fn from_str(s: &str) -> core::result::Result<Self, Self::Err> {
        match s {
            "None" | "none" | "n" => Ok(FlowControl::None),
            "Software" | "software" | "SW" | "sw" | "s" => Ok(FlowControl::Software),
            "Hardware" | "hardware" | "HW" | "hw" | "h" => Ok(FlowControl::Hardware),
            _ => Err(()),
        }
    }
}

/// Specifies which buffer or buffers to purge when calling [`clear`]
///
/// [`clear`]: trait.SerialPort.html#tymethod.clear
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum ClearBuffer {
    /// Specify to clear data received but not read
    Input,
    /// Specify to clear data written but not yet transmitted
    Output,
    /// Specify to clear both data received and data not yet transmitted
    All,
}

/// A struct containing all serial port settings
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SerialPortBuilder {
    /// The port name, usually the device path
    path: String,
    /// The baud rate in symbols-per-second
    baud_rate: u32,
    /// Number of bits used to represent a character sent on the line
    data_bits: DataBits,
    /// The type of signalling to use for controlling data transfer
    flow_control: FlowControl,
    /// The type of parity to use for error checking
    parity: Parity,
    /// Number of bits to use to signal the end of a character
    stop_bits: StopBits,
    /// Amount of time to wait to receive data before timing out
    timeout: Duration,
    /// The state to set DTR to when opening the device
    dtr_on_open: Option<bool>,
    /// Whether to enforce exclusive access to the port
    #[cfg(unix)]
    exclusive: bool,
}

impl SerialPortBuilder {
    /// Set the path to the serial port
    #[must_use]
    pub fn path<'a>(mut self, path: impl Into<std::borrow::Cow<'a, str>>) -> Self {
        self.path = path.into().into_owned();
        self
    }

    /// Set the baud rate in symbols-per-second
    #[must_use]
    pub fn baud_rate(mut self, baud_rate: u32) -> Self {
        self.baud_rate = baud_rate;
        self
    }

    /// Set the number of bits used to represent a character sent on the line
    #[must_use]
    pub fn data_bits(mut self, data_bits: DataBits) -> Self {
        self.data_bits = data_bits;
        self
    }

    /// Set the type of signalling to use for controlling data transfer
    #[must_use]
    pub fn flow_control(mut self, flow_control: FlowControl) -> Self {
        self.flow_control = flow_control;
        self
    }

    /// Set the type of parity to use for error checking
    #[must_use]
    pub fn parity(mut self, parity: Parity) -> Self {
        self.parity = parity;
        self
    }

    /// Set the number of bits to use to signal the end of a character
    #[must_use]
    pub fn stop_bits(mut self, stop_bits: StopBits) -> Self {
        self.stop_bits = stop_bits;
        self
    }

    /// Set the amount of time to wait to receive data before timing out
    ///
    /// <div class="warning">
    ///
    /// The accuracy is limited by the underlying platform's capabilities. Longer timeouts will be
    /// clamped to the maximum supported value which is expected to be in the magnitude of a few
    /// days.
    ///
    /// </div>
    #[must_use]
    pub fn timeout(mut self, timeout: Duration) -> Self {
        self.timeout = timeout;
        self
    }

    /// Set data terminal ready (DTR) to the given state when opening the device
    ///
    /// Note: On Linux, DTR is automatically set on open. Even if you set `dtr_on_open` to false,
    /// DTR will be asserted for a short moment when opening the port. This can't be prevented
    /// without kernel modifications.
    #[must_use]
    pub fn dtr_on_open(mut self, state: bool) -> Self {
        self.dtr_on_open = Some(state);
        self
    }

    /// Preserve the state of data terminal ready (DTR) when opening the device. Your outcome may
    /// vary depending on the operation system. For example, Linux sets DTR by default and Windows
    /// doesn't.
    #[must_use]
    pub fn preserve_dtr_on_open(mut self) -> Self {
        self.dtr_on_open = None;
        self
    }

    /// Set whether the port should be opened with exclusive access.
    ///
    /// By default, ports are opened with exclusive access. This is what you typically want as
    /// opening and accessing the very same port multiple times results in garbled data on or from
    /// the wire.
    #[cfg(unix)]
    #[must_use]
    pub fn exclusive(mut self, exclusive: bool) -> Self {
        self.exclusive = exclusive;
        self
    }

    /// Open a cross-platform interface to the port with the specified settings
    pub fn open(self) -> Result<SerialPort> {
        #[cfg(unix)]
        return posix::TTYPort::open(&self).map(SerialPort);

        #[cfg(windows)]
        return windows::COMPort::open(&self).map(SerialPort);

        #[cfg(not(any(unix, windows)))]
        Err(Error::new(
            ErrorKind::Unknown,
            "open() not implemented for platform",
        ))
    }


}


#[cfg(unix)]
pub(crate) mod sys {
    pub(crate) type SerialPort = crate::posix::TTYPort;
}
#[cfg(windows)]
pub(crate) mod sys {
    pub(crate) type SerialPort = crate::windows::COMPort;
}

/// A serial port.
///
/// This is the main type for interacting with serial ports. It wraps the
/// platform-specific implementation and provides a cross-platform API.
///
/// # Example
/// ```no_run
/// let port = serialport::new("/dev/ttyUSB0", 115_200)
///     .open()
///     .expect("Failed to open port");
/// `
#[derive(Debug)]
pub struct SerialPort(pub(crate) sys::SerialPort);

impl SerialPort {
    // Port settings getters

    /// Returns the name of this port if it exists.
    ///
    /// This name may not be the canonical device name and instead be shorthand.
    /// Additionally it may not exist for virtual ports.
    pub fn name(&self) -> Option<String> {
        self.0.name()
    }

    /// Returns the current baud rate.
    ///
    /// This may return a value different from the last specified baud rate depending on the
    /// platform as some will return the actual device baud rate rather than the last specified
    /// baud rate.
    pub fn baud_rate(&self) -> Result<u32> {
        self.0.baud_rate()
    }

    /// Returns the character size.
    ///
    /// This function returns `None` if the character size could not be determined. This may occur
    /// if the hardware is in an uninitialized state or is using a non-standard character size.
    /// Setting a baud rate with `set_char_size()` should initialize the character size to a
    /// supported value.
    pub fn data_bits(&self) -> Result<DataBits> {
        self.0.data_bits()
    }

    /// Returns the flow control mode.
    ///
    /// This function returns `None` if the flow control mode could not be determined. This may
    /// occur if the hardware is in an uninitialized state or is using an unsupported flow control
    /// mode. Setting a flow control mode with `set_flow_control()` should initialize the flow
    /// control mode to a supported value.
    pub fn flow_control(&self) -> Result<FlowControl> {
        self.0.flow_control()
    }

    /// Returns the parity-checking mode.
    ///
    /// This function returns `None` if the parity mode could not be determined. This may occur if
    /// the hardware is in an uninitialized state or is using a non-standard parity mode. Setting
    /// a parity mode with `set_parity()` should initialize the parity mode to a supported value.
    pub fn parity(&self) -> Result<Parity> {
        self.0.parity()
    }

    /// Returns the number of stop bits.
    ///
    /// This function returns `None` if the number of stop bits could not be determined. This may
    /// occur if the hardware is in an uninitialized state or is using an unsupported stop bit
    /// configuration. Setting the number of stop bits with `set_stop-bits()` should initialize the
    /// stop bits to a supported value.
    pub fn stop_bits(&self) -> Result<StopBits> {
        self.0.stop_bits()
    }

    /// Returns the current timeout.
    pub fn timeout(&self) -> Duration {
        self.0.timeout()
    }

    // Port settings setters

    /// Sets the baud rate.
    ///
    /// ## Errors
    ///
    /// If the implementation does not support the requested baud rate, this function may return an
    /// `InvalidInput` error. Even if the baud rate is accepted by `set_baud_rate()`, it may not be
    /// supported by the underlying hardware.
    pub fn set_baud_rate(&mut self, baud_rate: u32) -> Result<()> {
        self.0.set_baud_rate(baud_rate)
    }

    /// Sets the character size.
    pub fn set_data_bits(&mut self, data_bits: DataBits) -> Result<()> {
        self.0.set_data_bits(data_bits)
    }

    /// Sets the flow control mode.
    pub fn set_flow_control(&mut self, flow_control: FlowControl) -> Result<()> {
        self.0.set_flow_control(flow_control)
    }

    /// Sets the parity-checking mode.
    pub fn set_parity(&mut self, parity: Parity) -> Result<()> {
        self.0.set_parity(parity)
    }

    /// Sets the number of stop bits.
    pub fn set_stop_bits(&mut self, stop_bits: StopBits) -> Result<()> {
        self.0.set_stop_bits(stop_bits)
    }

    /// Sets the timeout for future I/O operations.
    ///
    /// <div class="warning">
    ///
    /// The accuracy is limited by the underlying platform's capabilities. Longer timeouts will be
    /// clamped to the maximum supported value which is expected to be in the magnitude of a few
    /// days.
    ///
    /// </div>
    pub fn set_timeout(&mut self, timeout: Duration) -> Result<()> {
        self.0.set_timeout(timeout)
    }

    // Functions for setting non-data control signal pins

    /// Sets the state of the RTS (Request To Send) control signal.
    ///
    /// Setting a value of `true` asserts the RTS control signal. `false` clears the signal.
    ///
    /// ## Errors
    ///
    /// This function returns an error if the RTS control signal could not be set to the desired
    /// state on the underlying hardware:
    ///
    /// * `NoDevice` if the device was disconnected.
    /// * `Io` for any other type of I/O error.
    pub fn write_request_to_send(&mut self, level: bool) -> Result<()> {
        self.0.write_request_to_send(level)
    }

    /// Writes to the Data Terminal Ready pin
    ///
    /// Setting a value of `true` asserts the DTR control signal. `false` clears the signal.
    ///
    /// ## Errors
    ///
    /// This function returns an error if the DTR control signal could not be set to the desired
    /// state on the underlying hardware:
    ///
    /// * `NoDevice` if the device was disconnected.
    /// * `Io` for any other type of I/O error.
    pub fn write_data_terminal_ready(&mut self, level: bool) -> Result<()> {
        self.0.write_data_terminal_ready(level)
    }

    // Functions for reading additional pins

    /// Reads the state of the CTS (Clear To Send) control signal.
    ///
    /// This function returns a boolean that indicates whether the CTS control signal is asserted.
    ///
    /// ## Errors
    ///
    /// This function returns an error if the state of the CTS control signal could not be read
    /// from the underlying hardware:
    ///
    /// * `NoDevice` if the device was disconnected.
    /// * `Io` for any other type of I/O error.
    pub fn read_clear_to_send(&mut self) -> Result<bool> {
        self.0.read_clear_to_send()
    }

    /// Reads the state of the Data Set Ready control signal.
    ///
    /// This function returns a boolean that indicates whether the DSR control signal is asserted.
    ///
    /// ## Errors
    ///
    /// This function returns an error if the state of the DSR control signal could not be read
    /// from the underlying hardware:
    ///
    /// * `NoDevice` if the device was disconnected.
    /// * `Io` for any other type of I/O error.
    pub fn read_data_set_ready(&mut self) -> Result<bool> {
        self.0.read_data_set_ready()
    }

    /// Reads the state of the Ring Indicator control signal.
    ///
    /// This function returns a boolean that indicates whether the RI control signal is asserted.
    ///
    /// ## Errors
    ///
    /// This function returns an error if the state of the RI control signal could not be read from
    /// the underlying hardware:
    ///
    /// * `NoDevice` if the device was disconnected.
    /// * `Io` for any other type of I/O error.
    pub fn read_ring_indicator(&mut self) -> Result<bool> {
        self.0.read_ring_indicator()
    }

    /// Reads the state of the Carrier Detect control signal.
    ///
    /// This function returns a boolean that indicates whether the CD control signal is asserted.
    ///
    /// ## Errors
    ///
    /// This function returns an error if the state of the CD control signal could not be read from
    /// the underlying hardware:
    ///
    /// * `NoDevice` if the device was disconnected.
    /// * `Io` for any other type of I/O error.
    pub fn read_carrier_detect(&mut self) -> Result<bool> {
        self.0.read_carrier_detect()
    }

    /// Gets the number of bytes available to be read from the input buffer.
    ///
    /// # Errors
    ///
    /// This function may return the following errors:
    ///
    /// * `NoDevice` if the device was disconnected.
    /// * `Io` for any other type of I/O error.
    pub fn bytes_to_read(&self) -> Result<u32> {
        self.0.bytes_to_read()
    }

    /// Get the number of bytes written to the output buffer, awaiting transmission.
    ///
    /// # Errors
    ///
    /// This function may return the following errors:
    ///
    /// * `NoDevice` if the device was disconnected.
    /// * `Io` for any other type of I/O error.
    pub fn bytes_to_write(&self) -> Result<u32> {
        self.0.bytes_to_write()
    }

    /// Discards all bytes from the serial driver's input buffer and/or output buffer.
    ///
    /// # Errors
    ///
    /// This function may return the following errors:
    ///
    /// * `NoDevice` if the device was disconnected.
    /// * `Io` for any other type of I/O error.
    pub fn clear(&self, buffer_to_clear: ClearBuffer) -> Result<()> {
        self.0.clear(buffer_to_clear)
    }

    // Misc methods

    /// Attempts to clone the `SerialPort`. This allow you to write and read simultaneously from the
    /// same serial connection. Please note that if you want a real asynchronous serial port you
    /// should look at [mio-serial](https://crates.io/crates/mio-serial) or
    /// [tokio-serial](https://crates.io/crates/tokio-serial).
    ///
    /// Also, you must be very careful when changing the settings of a cloned `SerialPort` : since
    /// the settings are cached on a per object basis, trying to modify them from two different
    /// objects can cause some nasty behavior.
    ///
    /// # Errors
    ///
    /// This function returns an error if the serial port couldn't be cloned.
    pub fn try_clone(&self) -> Result<SerialPort> {
        self.0.try_clone().map(SerialPort)
    }

    /// Start transmitting a break
    pub fn set_break(&self) -> Result<()> {
        self.0.set_break()
    }

    /// Stop transmitting a break
    pub fn clear_break(&self) -> Result<()> {
        self.0.clear_break()
    }
}

impl io::Read for SerialPort {
    fn read(&mut self, buf: &mut [u8]) -> io::Result<usize> {
        self.0.read(buf)
    }
}

impl io::Write for SerialPort {
    fn write(&mut self, buf: &[u8]) -> io::Result<usize> {
        self.0.write(buf)
    }
    fn flush(&mut self) -> io::Result<()> {
        self.0.flush()
    }
}

/// Contains all possible USB information about a `SerialPort`
#[derive(Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub struct UsbPortInfo {
    /// Vendor ID
    pub vid: u16,
    /// Product ID
    pub pid: u16,
    /// Serial number (arbitrary string)
    pub serial_number: Option<String>,
    /// Manufacturer (arbitrary string)
    pub manufacturer: Option<String>,
    /// Product name (arbitrary string)
    pub product: Option<String>,
    /// Physical port heirarchy
    pub location: Option<Location>,
    /// The interface index of the USB serial port. This can be either the interface number of
    /// the communication interface (as is the case on Windows and Linux) or the data
    /// interface (as is the case on macOS), so you should recognize both interface numbers.
    pub interface: Option<u8>,
}

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
/// Identify where a particular USB device is on the system.
pub struct Location {
    bus_id: String,
    port_chain: Vec<u8>,
}

impl Location {
    /// Create a new USB device location based on some string identifying the bus number, along with
    /// the path taken to a particular port.
    pub fn new(bus_id: String, port_chain: Vec<u8>) -> Self {
        Location { bus_id, port_chain }
    }

    /// Returns `true` if this Location is located below another Location in the bus hierarchy.
    pub fn is_descendant_of(&self, other: &Location) -> bool {
        self.bus_id == other.bus_id
            && self.port_chain.starts_with(&other.port_chain)
            && self.port_chain != other.port_chain
    }

    /// Returns the ID of the bus.
    pub fn bus_id(&self) -> &str {
        &self.bus_id
    }

    /// Returns a Vec of the port numbers needed to be traversed to get to this device.
    pub fn port_chain(&self) -> &[u8] {
        &self.port_chain
    }

    /// Returns the parent of this device, if any. Root objects have no parent.
    pub fn parent(&self) -> Option<Location> {
        if self.port_chain.len() <= 1 {
            None
        } else {
            Some(Location {
                bus_id: self.bus_id.clone(),
                port_chain: self.port_chain[0..self.port_chain.len() - 1].to_owned(),
            })
        }
    }
}

impl fmt::Display for Location {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> std::fmt::Result {
        // Use a location format similat to Linux' sysfs 'bus-port.port[....]'.
        //
        // TODO: Switch to Iterator::intersperse when it get stabilized and available to us.
        let port_chain = self
            .port_chain
            .iter()
            .map(|p| p.to_string())
            .collect::<Vec<_>>()
            .join(".");
        write!(f, "{}-{}", self.bus_id, port_chain)
    }
}

/// An error which can be returned when parsing a USB device location string.
// TODO: Derive Hash when our MSRV gives us an `IntErrorKind` implementing it.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ParseLocationError {
    kind: LocationErrorKind,
}

impl ParseLocationError {
    /// Returns the detailed cause for parsing a USB device location failing.
    pub fn kind(&self) -> &LocationErrorKind {
        &self.kind
    }
}

/// Enum to store the various types of errors that can cause parsing a USB device locaiton to fail.
// TODO: Derive Hash when our MSRV gives us an `IntErrorKind` implementing it.
#[derive(Clone, Debug, Eq, PartialEq)]
#[non_exhaustive]
pub enum LocationErrorKind {
    /// Parsing a port number in the port chain failed.
    Port(IntErrorKind),
    /// Parsing the top-level structure failed.
    TopLevel,
}

impl From<ParseIntError> for ParseLocationError {
    fn from(error: ParseIntError) -> ParseLocationError {
        // TODO: Switch to copying instead of cloning of ParseIntError once this is supported on our
        // MSRV too.
        #[allow(clippy::clone_on_copy)]
        ParseLocationError {
            kind: LocationErrorKind::Port(error.kind().clone()),
        }
    }
}

impl FromStr for Location {
    type Err = ParseLocationError;

    fn from_str(s: &str) -> std::result::Result<Location, Self::Err> {
        let mut splits = s.split('-');

        if let (Some(bus_id), Some(port_chain), None) =
            (splits.next(), splits.next(), splits.next())
        {
            let bus_id = String::from(bus_id);
            // We need to handle an empty port chain explicitly because otherwise the `split` would
            // result in an empty port string for which parsing would fail.
            let port_chain = if port_chain.is_empty() {
                Vec::new()
            } else {
                port_chain
                    .split('.')
                    .map(|p| p.parse())
                    .collect::<std::result::Result<Vec<u8>, _>>()?
            };

            Ok(Location { bus_id, port_chain })
        } else {
            Err(ParseLocationError {
                kind: LocationErrorKind::TopLevel,
            })
        }
    }
}

struct HexU16(u16);

impl std::fmt::Debug for HexU16 {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "0x{:04x}", self.0)
    }
}

impl std::fmt::Debug for UsbPortInfo {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let mut d = f.debug_struct("UsbPortInfo");
        d.field("vid", &HexU16(self.vid))
            .field("pid", &HexU16(self.pid))
            .field("serial_number", &self.serial_number)
            .field("manufacturer", &self.manufacturer)
            .field("product", &self.product)
            .field("location", &self.location)
            .field("interface", &self.interface)
            .finish()
    }
}

/// The physical type of a `SerialPort`
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub enum SerialPortType {
    /// The serial port is connected via USB
    UsbPort(UsbPortInfo),
    /// The serial port is connected via PCI (permanent port)
    PciPort,
    /// The serial port is connected via Bluetooth
    BluetoothPort,
    /// It can't be determined how the serial port is connected
    Unknown,
}

/// A device-independent implementation of serial port information
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
pub struct SerialPortInfo {
    /// The short name of the serial port
    pub port_name: String,
    /// The hardware device type that exposes this port
    pub port_type: SerialPortType,
}

/// Construct a builder of `SerialPort` objects
///
/// `SerialPort` objects are built using the Builder pattern through the `new` function. The
/// resultant `SerialPortBuilder` object can be copied, reconfigured, and saved making working with
/// multiple serial ports a little easier.
///
/// To open a new serial port:
/// ```no_run
/// serialport::new("/dev/ttyUSB0", 9600).open().expect("Failed to open port");
/// ```
pub fn new<'a>(path: impl Into<std::borrow::Cow<'a, str>>, baud_rate: u32) -> SerialPortBuilder {
    SerialPortBuilder {
        path: path.into().into_owned(),
        baud_rate,
        data_bits: DataBits::Eight,
        flow_control: FlowControl::None,
        parity: Parity::None,
        stop_bits: StopBits::One,
        timeout: Duration::from_millis(0),
        // Leave DTR alone when opening a device. We've started out with setting DTR on open (see
        // issues #29 and #204) but despite pleasing some Arduino use cases, this apparently caused
        // problems with other boards and when using pseudo terminals (see issues #243 and #251).
        //
        // To me it looks that the fallout from setting DTR on open by default gets on a
        // substantially larger area than the one benefitting from it, I finally decided to revert
        // this. Sorry for this back and forth, Christian.
        dtr_on_open: None,
        #[cfg(unix)]
        exclusive: true,
    }
}

/// Returns a list of all serial ports on system
///
/// It is not guaranteed that these ports exist or are available even if they're
/// returned by this function.
pub fn available_ports() -> Result<Vec<SerialPortInfo>> {
    #[cfg(unix)]
    return crate::posix::available_ports();

    #[cfg(windows)]
    return crate::windows::available_ports();

    #[cfg(not(any(unix, windows)))]
    Err(Error::new(
        ErrorKind::Unknown,
        "available_ports() not implemented for platform",
    ))
}

#[cfg(test)]
mod test {
    use super::*;
    use rstest::rstest;

    /// Checks parameters and that default values don't get charged by accident.
    #[rstest]
    fn builder_new() {
        let builder = new("port_test_dummy", 12345);

        assert_eq!(builder.path, "port_test_dummy");
        assert_eq!(builder.baud_rate, 12345);

        assert_eq!(builder.data_bits, DataBits::Eight);
        assert_eq!(builder.flow_control, FlowControl::None);
        assert_eq!(builder.parity, Parity::None);
        assert_eq!(builder.stop_bits, StopBits::One);
        assert_eq!(builder.timeout, Duration::ZERO);
        assert_eq!(builder.dtr_on_open, None);
        #[cfg(unix)]
        assert!(builder.exclusive);
    }

    // Checks that the builder's exclusive method changes the state accordingly.
    #[cfg(unix)]
    #[rstest]
    fn builder_exclusive() {
        let builder = new("port_test_dummy", 12345);
        assert!(builder.exclusive);

        let builder = builder.exclusive(false);
        assert!(!builder.exclusive);

        let builder = builder.exclusive(true);
        assert!(builder.exclusive);
    }

    #[rstest]
    fn usbportinfo_debug_representation() {
        let info = UsbPortInfo {
            manufacturer: Some(String::from("your manufacutrer here")),
            vid: 0xbade,
            pid: 0xaffe,
            product: Some(String::from("your product here")),
            serial_number: Some(String::from("your serial_number here")),
            location: Some(Location::new(String::from("001"), vec![1, 2, 3])),
            interface: Some(42),
        };
        let formatted = format!("{:?}", info);

        // Set the expectiation for the debug representation basend on a "snapshot" of the current
        // one, manually cross-checked to contain a VID and PID in hexadecimal digits.
        let expected = String::from("UsbPortInfo { vid: 0xbade, pid: 0xaffe, serial_number: Some(\"your serial_number here\"), manufacturer: Some(\"your manufacutrer here\"), product: Some(\"your product here\"), location: Some(Location { bus_id: \"001\", port_chain: [1, 2, 3] }), interface: Some(42) }");

        assert_eq!(formatted, expected);
    }

    mod usbportinfo_location {
        use super::*;

        // Empty fields are corner cases when we are not restricting the input inputs to
        // `Location::new`. Let's have some test to ensure that they behave at least in a defined
        // manner.
        #[rstest]
        #[case(Location { bus_id: String::new(), port_chain: vec![] }, "-")]
        #[case(Location { bus_id: String::from("1"), port_chain: vec![] }, "1-")]
        #[case(Location { bus_id: String::new(), port_chain: vec![1] }, "-1")]
        fn display_empty_fields(#[case] location: Location, #[case] display: &str) {
            assert_eq!(format!("{}", location), display);
        }

        #[rstest]
        #[case(Location { bus_id: String::from("bus"), port_chain: vec![1, 2, 3]})]
        #[case(Location { bus_id: String::from("1"), port_chain: vec![1, 2, 3]})]
        #[case(Location { bus_id: String::from("001"), port_chain: vec![1, 2, 3]})]
        fn display_from_str_cycle(#[case] start: Location) {
            let display = format!("{}", start);
            let from_str = Location::from_str(&display).unwrap();

            assert_eq!(start, from_str);
        }

        #[rstest]
        fn display_simple() {
            let location = Location {
                bus_id: String::from("bus"),
                port_chain: vec![1, 2, 3],
            };

            assert_eq!(format!("{}", location), "bus-1.2.3",)
        }

        // Empty fields are corner cases when we are not restricting the input inputs to
        // `Location::new`. Let's have some test to ensure that they behave at least in a defined
        // manner.
        #[rstest]
        #[case("-", Location { bus_id: String::new(), port_chain: vec![]})]
        #[case("1-", Location { bus_id: String::from("1"), port_chain: vec![]})]
        #[case("-1", Location { bus_id: String::new(), port_chain: vec![1]})]
        fn from_str_empty_fields(#[case] from: &str, #[case] location: Location) {
            assert_eq!(Location::from_str(from).unwrap(), location);
        }

        #[rstest]
        fn from_str_simple() {
            assert_eq!(
                Location::from_str("bus-1").unwrap(),
                Location {
                    bus_id: String::from("bus"),
                    port_chain: vec![1],
                }
            );

            assert_eq!(
                Location::from_str("bus-255").unwrap(),
                Location {
                    bus_id: String::from("bus"),
                    port_chain: vec![255],
                }
            );

            assert_eq!(
                Location::from_str("bus-1.2.3.4.5").unwrap(),
                Location {
                    bus_id: String::from("bus"),
                    port_chain: vec![1, 2, 3, 4, 5],
                }
            );
        }

        #[rstest]
        fn from_str_simple_invalid() {
            matches!(
                Location::from_str("").unwrap_err().kind(),
                LocationErrorKind::TopLevel
            );
            matches!(
                Location::from_str("bus").unwrap_err().kind(),
                LocationErrorKind::TopLevel
            );
            matches!(
                Location::from_str("bus-a").unwrap_err().kind(),
                LocationErrorKind::Port(_)
            );
            matches!(
                Location::from_str("bus-256").unwrap_err().kind(),
                LocationErrorKind::Port(_)
            );
            matches!(
                Location::from_str("bus-1-1").unwrap_err().kind(),
                LocationErrorKind::TopLevel
            );
            matches!(
                Location::from_str("bus-1..2").unwrap_err().kind(),
                LocationErrorKind::TopLevel
            );
            matches!(
                Location::from_str("bus-1.2.").unwrap_err().kind(),
                LocationErrorKind::TopLevel
            );
        }

        #[rstest]
        fn is_descendand_of() {
            let child = Location {
                bus_id: String::from("bus"),
                port_chain: vec![1, 2, 3],
            };
            let parent = Location {
                bus_id: String::from("bus"),
                port_chain: vec![1, 2],
            };
            let grandparent = Location {
                bus_id: String::from("bus"),
                port_chain: vec![1],
            };
            let empty_port_chain = Location {
                bus_id: String::from("bus"),
                port_chain: vec![],
            };

            assert!(child.is_descendant_of(&empty_port_chain));
            assert!(parent.is_descendant_of(&empty_port_chain));
            assert!(grandparent.is_descendant_of(&empty_port_chain));
            assert!(!empty_port_chain.is_descendant_of(&empty_port_chain));

            assert!(child.is_descendant_of(&grandparent));
            assert!(parent.is_descendant_of(&grandparent));
            assert!(!grandparent.is_descendant_of(&grandparent));
            assert!(!empty_port_chain.is_descendant_of(&grandparent));

            assert!(child.is_descendant_of(&parent));
            assert!(!parent.is_descendant_of(&parent));
            assert!(!grandparent.is_descendant_of(&parent));
            assert!(!empty_port_chain.is_descendant_of(&parent));

            assert!(!child.is_descendant_of(&child));
            assert!(!parent.is_descendant_of(&child));
            assert!(!grandparent.is_descendant_of(&child));
            assert!(!empty_port_chain.is_descendant_of(&child));

            let different_parent = Location {
                bus_id: String::from("another_bus"),
                port_chain: vec![1, 2],
            };

            assert!(!child.is_descendant_of(&different_parent));
        }

        #[rstest]
        fn parent() {
            let child = Location {
                bus_id: String::from("bus"),
                port_chain: vec![1, 2, 3],
            };
            let parent = Location {
                bus_id: String::from("bus"),
                port_chain: vec![1, 2],
            };
            let grandparent = Location {
                bus_id: String::from("bus"),
                port_chain: vec![1],
            };
            let empty_port_chain = Location {
                bus_id: String::from("bus"),
                port_chain: vec![1],
            };

            assert_eq!(child.parent(), Some(parent.clone()));
            assert_eq!(parent.parent(), Some(grandparent.clone()));

            assert!(grandparent.parent().is_none());
            assert!(empty_port_chain.parent().is_none());
        }
    }
}
